export const GET_LOGGEDIN_USER = 'GET_LOGGEDIN_USER';
export const GET_LOGGEDIN_USER_TYPE = 'GET_LOGGEDIN_USER_TYPE';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICE = 'GET_SERVICE';
export const SET_LOADING = 'SET_LOADING';
