import React, { useEffect, useContext, useState, Fragment } from "react";
import { Link } from "react-router-dom";
import Axios from "axios";

import "react-web-tabs/dist/react-web-tabs.css";



const AccountVerification = (props) => {


  

  return (
    <Fragment>
    <section className="hero home-hero ui-full-bg-norm" style={{backgroundImage: 'url("../../images/assets/bg@twofa.png)'}}>
                <div className="container">
                  
                    <div className="ui-wrapper-large">

                        <div className="row">

                            <div className="col-md-5">
                             
                           <div className="logo-auth">
                           <div className="text-center">
                                  <img src="../../images/assets/scribry.png" alt='img'/>
                            </div>
                            
                           </div>
                                <div className="c--box ui-box-shadow-dark-fade mrgt3">
          

                                    <form>
                                       
                                            <>
                                                <div className="form-group">
                                                <h3 className='font-gilroybold brand-purpledark fs-22 mb-1 text-center mrgt2 mrgb1'>Account Verification </h3>
                                                <p className='font-gilroy brand-purpledark fs-14 mb-1 text-center mrgt1 mrgb2'>You have enabled two-factor authentication on your Scribry account. 
                                                Please enter the 6-digit code generated by your authenticaton app. </p>
                                                <h5 className="font-gilroy brand-purpledark fs-12 mb-1 text-center mrgt2 mrgb1">Enter 2FA code below</h5>
                                                   
                                                </div>

                                                    <div className="row">
                                                        <div className="col-md-2">
                                                            <div className="form-group">
                                                               
                                                                <input type="email" className="font-gilroybold fs-25 form-control text-center" placeholder="0" />
                                                            </div>
                                                        </div>
                                                        <div className="col-md-2">
                                                            <div className="form-group">
                                                                
                                                                <input type="email" className="font-gilroybold  fs-25 form-control text-center" placeholder="0" />
                                                            </div>
                                                        </div>
                                                        <div className="col-md-2">
                                                            <div className="form-group">
                                                                
                                                                <input type="email" className="font-gilroybold  fs-25 form-control text-center" placeholder="0" />
                                                            </div>
                                                        </div>
                                                        <div className="col-md-2">
                                                            <div className="form-group">
                                                                
                                                                <input type="email" className="font-gilroybold  fs-25 form-control text-center" placeholder="0" />
                                                            </div>
                                                        </div>
                                                        <div className="col-md-2">
                                                            <div className="form-group">
                                                               
                                                                <input type="email" className="font-gilroybold fs-25 form-control text-center" placeholder="0" />
                                                            </div>
                                                        </div>
                                                        <div className="col-md-2">
                                                            <div className="form-group">
                                                                
                                                                <input type="email" className="font-gilroybold  fs-25 form-control text-center" placeholder="0" />
                                                            </div>
                                                        </div>
                                                    </div>

                                               


                                                <div className="mrgt mrgb">
                                                   
                                                           
                                                     
                                                            <Link to="" className="btn big-btn hero-start btn-block bg-brand-yellow onmineshaft font-gilroybold">Continue</Link>
                                                     
                                                </div>
                                                <div className="form-group ui-text-center ">
                                                    <Link to="/signup"  className="font-gilroy fs-14 brand-o"> Dont have an account? {' '}<span className="fs-14 brand-Lyellow">Regsiter</span></Link>
                                                </div>
                                             
                                               
                                            </>
                                       

                                      

                                    </form>
                                    

                                </div>

                               
                            </div>
                            
                        </div>

                    </div>
                </div>
            </section>
    </Fragment>
  );
};

export default AccountVerification;
